language: python
cache:
  pip: true
git:
  depth: 1

env:
  global:
  - NETFRAME_COVERAGE=1

jobs:
  include:
    - name: "linux-x86_64-3.7-gcc8"
      os: linux
      python: 3.7.4
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - BASE_PYTHON_VERSION=3.7 PYTHON_VERSION=3.7.4 CC=gcc-8 CXX=g++-8 COV=gcov-8
    - name: "linux-x86_64-3.8-gcc8"
      os: linux
      python: 3.8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - BASE_PYTHON_VERSION=3.8 PYTHON_VERSION=3.8.0 CC=gcc-8 CXX=g++-8 COV=gcov-8

      
before_install:
  - sudo sysctl -w net.ipv6.conf.all.disable_ipv6=0
  - sudo ln -s "/usr/bin/${CC}" /usr/local/bin/gcc
  - sudo ln -s "/usr/bin/${CXX}" /usr/local/bin/g++

install:
  # use our own virtual environment for mypy stubs
  - deactivate && virtualenv -p /opt/python/$PYTHON_VERSION/bin/python${BASE_PYTHON_VERSION} ENV  
  - source ENV/bin/activate
  - pip install --upgrade pip
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - export PATH="$PATH:$HOME/.poetry/bin"
  # temp fix for poetry and python3.8
  - if [[ $BASE_PYTHON_VERSION == 3.8 ]]; then ln -s ~/.poetry/lib/poetry/_vendor/py3.7 ~/.poetry/lib/poetry/_vendor/py3.8; fi
  - mkdir -p build/temp.linux-x86_64-${BASE_PYTHON_VERSION}
  - pushd build/temp.linux-x86_64-${BASE_PYTHON_VERSION}
  # force output from bulding on the C++ extension hidden by poetry
  - cmake -DPYTHON_EXECUTABLE:FILEPATH=../../ENV/bin/python ../.. && make VERBOSE=1 all
  - popd
  - poetry install -vvv
  - pip install cpp-coveralls python-coveralls

script:
  - poetry run pylint snmp_fetch tests plugins
  - poetry run flake8 snmp_fetch tests plugins
  - MYPYPATH=stubs/linux-x86_64-${BASE_PYTHON_VERSION} poetry run mypy -p snmp_fetch -p tests -p plugins
  - poetry run bandit -r snmp_fetch
  - poetry run pytest -v tests --cov

after_success:
  - cpp-coveralls --gcov="${COV}" -b build/temp.linux-x86_64-${BASE_PYTHON_VERSION}/CMakeFiles/api.dir/snmp_fetch/snmp/api/ --gcov-options '\-lp' -i snmp_fetch/snmp/api --dump cpp-coveralls.json 
  - coveralls --merge_file cpp-coveralls.json
