language: python
cache: pip

matrix:
  include:
    - name: "Python 3.7 and GCC 7"
      python: "3.7"
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libperl-dev
      env:
        - CC=gcc-7
        - CXX=g++-7

    - name: "Python 3.7 and GCC 8"
      python: "3.7"
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - libperl-dev
      env:
        - CC=gcc-8
        - CXX=g++-8

    - name: "Python 3.7 and GCC 9"
      python: "3.7"
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
            - libperl-dev
      env:
        - CC=gcc-9
        - CXX=g++-9

    - name: "Python 3.7 and Clang 6"
      python: "3.7"
      os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-6.0
          packages:
            - clang-6.0
            - libperl-dev
      env:
        - CC=clang-6.0
        - CXX=clang++-6.0

    - name: "Python 3.7 and Clang 7"
      python: "3.7"
      os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-7
          packages:
            - clang-7
            - libperl-dev
      env:
        - CC=clang-7
        - CXX=clang++-7

    - name: "Python 3.7 and Clang 8"
      python: "3.7"
      os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-8
          packages:
            - clang-8
            - libperl-dev
      env:
        - CC=clang-8
        - CXX=clang++-8

    - name: "Python 3.7 and Clang 9"
      python: "3.7"
      os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-9
          packages:
            - clang-9
            - libperl-dev
      env:
        - CC=clang-9
        - CXX=clang++-9
 
before_install:
  - sudo ln -s "/usr/bin/${CC}" /usr/local/bin/gcc
  - sudo ln -s "/usr/bin/${CXX}" /usr/local/bin/g++
  - gcc -v && g++ -v && cmake --version
  - wget https://dl.bintray.com/boostorg/release/1.70.0/source/boost_1_70_0.tar.gz -O /tmp/boost.tar.gz
  - tar -xvf /tmp/boost.tar.gz boost_1_70_0/boost
  - export CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH:$PWD/boost_1_70_0/
  - wget https://github.com/pybind/pybind11/archive/v2.3.0.tar.gz -O /tmp/pybind11.tar.gz
  - tar -xvf /tmp/pybind11.tar.gz
  - export CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH:$PWD/pybind11-2.3.0/include/
  - wget https://sourceforge.net/projects/net-snmp/files/net-snmp/5.8/net-snmp-5.8.tar.gz/download -O net-snmp.tar.gz
  - tar xzfv net-snmp.tar.gz
  - pushd net-snmp-5.8
  - ./configure --enable-ipv6 --with-defaults
  - make && sudo make install
  - sudo ldconfig -v
  - popd

install:
  - pip install --upgrade pip
  - pip install poetry
  - poetry install -v

script:
  - pylint snmp_fetch tests
  - flake8 snmp_fetch tests
  - mypy -m snmp_fetch -m tests
  - bandit -r snmp_fetch
  - poetry run pytest -v --cov --hypothesis-show-statistics tests/

after_success:
  - coveralls
